get:
  tags:
    - 상품API version 2
  summary: 상품 상세 조회
  parameters:
    - in: path
      name: product_idx
      schema:
        type: string
      description: |
        상품 고유번호
      required: true

  responses:
    '200':
      description: 상품 데이터 조회 성공
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              success:
                type: boolean
                example: true
              message:
                type: string
                example: '데이터 조회 성공'
              data:
                type: object
                example: {
                  "img": [
                      "https://s3.ap-northeast-2.amazonaws.com/sopt.seongjin.com/(썸네일)+차돌김치볶음밥+300g.jpg"
                  ],
                  "name": "브랜드이름",
                  "detail_name": "카테고리(계란/메추리알) 상품 1",
                  "sale_ratio": 0,
                  "saled_price": 2600,
                  "price": 2600,
                  "detail_img": [
                      "https://s3.ap-northeast-2.amazonaws.com/sopt.seongjin.com/차돌김치볶음밥+300g+(1).jpg",
                      "https://s3.ap-northeast-2.amazonaws.com/sopt.seongjin.com/차돌김치볶음밥+300g+(2).jpg"
                  ],
                  "shared_count": 3,
                  "like": 0,
                  "count": 5,
                  "is_adult": false
                }
    '400':
      $ref: '../../components/responses.yaml#400-NULL_VALUE'
    '500  ':
      $ref: '../../components/responses.yaml#500-INTERNAL_SERVER_ERROR'