get:
  tags:
    - 상품API version 2
  summary: 상품 리스트 조회
  parameters:
    - in: query
      name: b_code
      schema:
        type: string
      description: |
        법정동코드 (b_code 또는 h_code 중 하나만 입력)
      required: true
    - in: query
      name: h_code
      schema:
        type: string
      description: |
        행정동코드 (b_code 또는 h_code 중 하나만 입력)
      required: true
    - in: query
      name: category_idx
      schema:
        type: string
      description: |
        카테고리 고유번호 (cateogory_idx 또는 keyword 중 하나만 입력)
      required: true
    - in: query
      name: keyword
      schema:
        type: string
      description: |
        검색 키워드 (cateogory_idx 또는 keyword 중 하나만 입력)
      required: true
    - in: query
      name: sort
      schema:
        type: string
      description: |
        상품 정렬 (판매순, 인기순, 낮은가격순, 높은가격순, 많은리뷰순, 최신순)
      required: true
    - in: query
      name: offset
      schema:
        type: string
      description: |
        검색 시작 지점
      required: true
    - in: query
      name: count
      schema:
        type: string
      description: |
        검색 갯수
      required: true

  responses:
    '200':
      description: 상품 데이터 조회 성공
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              success:
                type: boolean
                example: true
              message:
                type: string
                example: '데이터 조회 성공'
              data:
                type: object
                properties:
                  total_count:
                    type: integer
                    example: 150
                  products:
                    type: array
                    example: [
                      {
                        "product_idx": "6020c547f5bd68cfe180eab0",
                        "main_img": "https://s3.ap-northeast-2.amazonaws.com/sopt.seongjin.com/(썸네일)+차돌김치볶음밥+300g.jpg",
                        "like": 0,
                        "detail_name": "카테고리(계란/메추리알) 상품 1",
                        "sale_ratio": 0.22,
                        "saled_price": 600,
                        "price": 770,
                        "is_adult": false
                      },
                      {
                        "product_idx": "6020c70cf5bd68cfe180ede6",
                        "main_img": "https://s3.ap-northeast-2.amazonaws.com/sopt.seongjin.com/(썸네일)+차돌김치볶음밥+300g.jpg",
                        "like": 0,
                        "detail_name": "카테고리(계란/메추리알) 상품 2",
                        "sale_ratio": 0,
                        "saled_price": 2600,
                        "price": 2600,
                        "is_adult": false
                      }
                    ]
    '400':
      $ref: '../../components/responses.yaml#400-NULL_VALUE'
    '500  ':
      $ref: '../../components/responses.yaml#500-INTERNAL_SERVER_ERROR'